repo: 'banner'
canvasCourse: 'web-dev-2'

inherit:
  - naming-restrict-live
  - git-2
  - html
  - google-fonts
  - img-flex
  - css
  - responsive-css
  - typografier
  - css-order-type-main
  - border-box

html:
  - path: 'index.html'
    has:
      - '.banner'
      - '.banner > .banner-content'
      - '.banner > img'
      - '.banner-content > div'
      - '.banner-content > div > h1'
      - '.banner-content > div > p'
    search:
      - 'Space & Time Explorer Person'
      - 'text-'
      - 'max-length|wrapper'

css:
  - path: 'css/main.css'
    search:
      - 'position: relative'
      - 'position: absolute'
      - 'bottom'
      - 'left'
      - 'width'
      - 'overflow: hidden'
      - 'max-height'
    search_not:
      - 'font-size'
      - 'margin'
      - 'padding'
      - 'line-height'

screenshots:
  - path: 'index.html'
    sizes: [608, 960, 1440]
